FROM python:3.5-alpine

# Set the file maintainer (your name - the file's author)
MAINTAINER Olivier Chantereau

# Set env variables used in this Dockerfile (add a unique prefix, such as DOCKYARD)
# Local directory with project source
ENV DOCKER_SRC=.
# Directory in container for all project files
ENV DOCKER_SRVHOME=/srv
# Directory in container for project source files
ENV DOCKER_SRVPROJ=/srv/application

# Update the default application repository sources list
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y python python-pip


